apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hello-app"
  namespace: "default"
  labels: 
    app: "myapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "myapp"
  template:
    metadata:
      labels:
        app: "myapp"
    spec:
      containers:
      - name: "my-app"
        image: "index.docker.io/vplma/gcp-terraform:gcp"

---


apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-service
  namespace: default
spec:
  ports:
  - nodePort: 30000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: myapp
  type: LoadBalancer
